title: 'Adam Fistler Services'
name: 'Adam Fistler'
address:
  street: 'New Office Comming Soon'
  city: 'South Jersey or Philadelphia?'
  state: 'NJ'
  zip: '08000' 
phone: '<a href="tel:(856) 209-3350">(856) 209-3350</a>'
email: '<a href="mailto:afistler.services@gmail.com">afistler.services@gmail.com</a>'
footer:
  - 'Copyright Â© 2023 - Adam Fistler Services - Camden, NJ.  All Rights Reserved.'
  - 'Adam Fistler &nbsp; New Office Coming Soon <!-- PHONE -->'
  - 'Server South Jersey and Philadelphia with the latest in hypnosis, addiction alternatives, astrology, graphology, and technology.'
  - 'South Jerseys Choice for Holistic Healing.'
menu:
  Home: /html/main/home.html
  GoFundMe: /html/main/go_fund_me.html
  Hypnosis:
    Professional Experience: /html/articles/hypnosis/bhc.html
    About Hypnosis: /html/hypnosis/about_hypnosis.html
    Hypnosis Services: /html//hypnosis/hypnosis_services.html
    Testimonials: /html/hypnosis/testimonials.html
    Anger: /html/hypnosis/anger.html
    Weight Loss: /html/hypnosis/weight_loss.html
    Smoking Cessation: /html/hypnosis/smoking_cessation.html
  Addiction Services: /html/addiction/addiction_services.html
  Astrology: /html/astrology/astrology.html
  Handwriting Analysis: /html/graphology/graphology.html
  Technology:
    Projects: /html/technology/projects.html
    Artwork: /html/technology/artwork.html
    Resume: /html/technology/resume.html
  Upcoming Events: /html/main/upcoming_events.html
  Articles: /html/articles/articles.html
  Contact Us: /html/main/contact_us.html
hypnosis:
  issue_columns: 4 
  issues:
    - Addiction
    - Adderall Abuse
    - Substance Abuse
    - Heroin Abuse
    - Opiate / Opioid Abuse
    - Oxycodone (Percocet) Abuse
    - Oxycodine Abuse
    - Hydrocodone (Vicodin) Abuse 
    - Alcohol Abuse
    - Alcoholism
    - Anger
    - Anxiety
    - Bad Habits
    - Benzodiazepine Abuse
    - Xanax Abuse
    - Klonopin Abuse
    - Bruxism (Teeth Grinding)
    - Cocaine Abuse
    - Crack Abuse
    - Confidence
    - Diabetes
    - Emotional Eating
    - Exercise Habits
    - Fatigue
    - Fear of Failure
    - Focus
    - Forgiveness
    - Grief Issues
    - Guilt
    - Headaches
    - Heroin Addiction
    - Hopelessness
    - Irrational Fears (Phobias)
    - Irritability
    - Laziness
    - Methamphetamine Abuse
    - Migraine Headaches
    - Mood Swings
    - Nail Biting
    - Nose Picking
    - Pain Control / Pain Management
    - Panic Attacks
    - Procrastination
    - Relationship Issues
    - Relaxation
    - Road Rage
    - Self Discipline
    - Self Esteem
    - Self Image
    - Self Sabotage
    - Skin Problems
    - Smoking Cessation
    - Social Anxiety (Shyness)
    - Stress
    - Stuttering
    - Tension
    - Test Anxiety
    - Tiredness
    - Trust Issues
    - Weight Loss
    - Worry
    - Worthlessness
keywords:
  - Addiction
  - "Substance Abuse"
  - Astrology
  - "Handwriting Analysis"
  - Technology
  - Hypnosis
  - Hypnotism
  - Hypnotist
  - Zodiac
  - "Natal Chart" 
  - "Birth Chart"
  - "Birth Chart Reading"
  - "Natal Chart Reading"
